apiVersion: v1
kind: Service
metadata:
  name: web-test 
spec:
  selector:
    app: web-test 
    tier: backend
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090 
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test 
spec:
  selector:
    matchLabels:
      app: web-test 
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: web-test 
        tier: backend
        track: stable
    spec:
      containers:
        - name: web-test 
          image: "victor13533/web-test"
          ports:
            - name: http
              containerPort: 9090 
          env:
            - name: PGHOST
              value: test-db 
            - name: APP_PORT
              value: "9090"
