apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: web-test-ui 
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: web-test-ui
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: web-test-ui 
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "victor13533/web-test-ui"
