apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx-conf: |
    upstream hello {
        server hello;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://hello;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: web-test-ui 
spec:
  selector:
    app: web-test-ui 
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test-ui 
spec:
  selector:
    matchLabels:
      app: web-test-ui
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: web-test-ui 
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "victor13533/web-test-ui"
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf 
          items:
            - key: nginx.conf
              path: nginx.conf
